Console.ForegroundColor = ConsoleColor.DarkRed;
Console.WriteLine("Soletrar CADEIRA");
Console.ResetColor();
Console.ReadKey();
Console.Write("=");
Console.ReadKey();
Console.Write("C");
Console.ReadKey();
Console.Write("-A");
Console.ReadKey();
Console.Write("-D");
Console.ReadKey();
Console.Write("-E");
Console.ReadKey();
Console.Write("-I");
Console.ReadKey();
Console.Write("-R");
Console.ReadKey();
Console.Write("-A");